# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171104_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='flag_suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
