# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_analysis_flag_suppressed'),
        ('projects', '0007_analysis_flag_suppressed'),
    ]

    operations = [
    ]
